### ISSUE TITLE
Make assetbrowser dockable

### ISSUE THREAD

**Issue by philippTheCat** [Traderain/Wolven-kit#100]
**Is your feature request related to a problem? Please describe.**
When using wolvenkit and its assetbrowser on the same display the windows hide eachother when activated.

**Describe the solution you'd like**
Assetbrowser should be dockable (and docked by default?)

**Comment by Traderain** [comment]
I took the design from the leaked Redengine that you basically do your stuff and the asset browser is minimized. When you need something you just bring it up and add some files from it. I haven't had an occurence that that would happen but I will try to see what you mean by it. I am developing on a dual monitor setup so that may be that made me not notice the inconvienence.

**Comment by philippTheCat** [comment]
In the beginning of development I needed to view quite a few files to get situated (how does everything work and connect etc), so I had the assetbrowser open a lot. In the end I just added all files I could possibly need.

**Comment by Traderain** [comment]
yeah that may happen. If this becomes an issue later on we can discuss how to change it.

**Comment by rfuzzo** [comment]
Implementing this is easy enough, and it looks decent. But minimizing the Floating Window is awkward and bugged in the docpanelsuite. (https://github.com/dockpanelsuite/dockpanelsuite/issues/526)

¯\_(ツ)_/¯
