### ISSUE TITLE
Model renderer

### ISSUE THREAD

**Issue by Traderain** [Traderain/Wolven-kit#11]
Something like Noesis but a little more simple.
- [x] Simple OpenGL scene
- [x] Model renderer
- [x] Texture loader for the models
- [x] Bones
- [x] Animations
- [ ] Import from DAE,FBX
- [ ] Export to DAE,FBX

![renderer](https://user-images.githubusercontent.com/7668964/42332218-b9d81c74-8077-11e8-9ae6-20b81e2148ac.png)

![image](https://cloud.githubusercontent.com/assets/6411732/23142700/90a1cb82-f7bd-11e6-8626-cd6e93ebc5c9.png)

**Comment by athompson673** [comment]
I have the version currently up on nexusmods.com, and textures aren't parsed correctly (message box: "missing texture. Have you extracted the textures properly?"). They also are super goofed up when you preview just the texture itself. Is this fixed in the current branch? my current workaround is to open the textures separately with the windows texture viewer from Nvidia (https://www.nvidia.com/object/windows_texture_viewer.html) to make sure I've got the right file.

**Comment by vonLeebpl** [comment]
Should we come back to this? I think we have all we need now and it's a matter of refactoring plus some new coding to put it together into main track. What you think?

**Comment by Traderain** [comment]
That would be awesome! Some guy made some code to import new animations so this would be priority to work well. I am trying to create a terrain renderer at the moment as well. So if this would work wall that would help the project really well. We could preview items properly in asset browser even.

**Comment by vonLeebpl** [comment]
I will look into that.
