### ISSUE TITLE
w3speech format

### ISSUE THREAD

**Issue by DellCliff** [Traderain/Wolven-kit#34]
Hi together. Anyone here knows what the 8 bytes behind the wem bytes block in the .w3speech files are supposed to mean/how to decode/encode them?

**Comment by DellCliff** [comment]
I can pretty much read/write everything else of that w3speech format, except for those 8 bytes.

**Comment by DellCliff** [comment]
If you can help me out, I can send you a pull request for a complete reader/writer for those files.

**Comment by Traderain** [comment]
Hi
Thanks for helping with the project 👍 . Since I am coding most stuff myself I haven't really had time to code much w3speech related just an extractor. Rmemr has mod a tool for it but its commandline only and is in rust (https://github.com/rmemr/w3.phoneme-extractor) you can probably look at that. If you can't figure it out then if you make a pull request with the reader/writer I will reverse engineer those 8 bytes after I have finnaly fixed the xbm converter.

**Comment by DellCliff** [comment]
Thanks. I've looked at rmemr's stuff, sadly this particular repository only deals with audio files, not the w3speech format. He does have a file packer/unpacker on nexusmods which is not open source though. Bad luck. Guess I have to keep looking.

**Comment by Murzinio** [comment]
Or just ask rmemr on nexus.

**Comment by Traderain** [comment]
@DellCliff I'll ask him to give some input into this

**Comment by rmemr** [comment]
```
pub struct SpeechVoData {
    id: u32,
    duration: f32,      // duration in seconds
    unknown: u32,       // set to constant 4
    audio: Vec<u8>,
    cr2w: Vec<u8>,
}
```
duration can differ from audio length. it clips the audio if shorter.

**Comment by DellCliff** [comment]
@rmemr 
Thanks, just what was missing. Gonna do some testing.
