### ISSUE TITLE
Folder structure in DLC

### ISSUE THREAD

**Issue by KoalaNalle** [Traderain/Wolven-kit#85]
Currently upon loading assets to "DLC" and the packing the DLC doesn't produce working DLC.

Currently kit creates 
files\DLC\\Bundle\\[files]

Upon packing the metadata path points to \[files]
While the game need DLC files to be:
\dlc\\[DLCNAME]\\[files]

The workaround now is to add the assets:
Create the folders:
files\DLC\Bundle\\**dlc**\\**dlcname**\\[files]

and copy the assets to needed to be used to [files]

[files] can be any structure one wants to use.

**Comment by KoalaNalle** [comment]
Ideally the folder structure could be introduced upon packing the DLC part. It would require that there would be a check if user has already created the proper structure.

**Comment by Traderain** [comment]
Yes that would be indeed the best but for that we (or rather I) need to create a dlc mounter generator and that need a little more work on the cr2w files part first since creating a completely new one from scratch is a bit funky.
![image](https://user-images.githubusercontent.com/6411732/42323743-7900421e-8061-11e8-8b30-70fb9418487f.png)
